Add ON_GLOBAL_NICE_CALL macro
apriorit/gmock-global pull request #14
Opened 2024-06-17 10:58 UTC by artek-koltun

`ON_GLOBAL_CALL` can be used to set default behavior. However, when such a mock is called, it produces a warning, cluttering the test output that uninteresting calls were performed. Such warnings can be useful in some situation, however, in many cases we can safely suppress them.

`gmock-global` missed a way to control those warnings, and `ON_GLOBAL_NICE_CALL` should resolve this issue.

For additional information pls see [gmock cook book](https://github.com/google/googletest/blob/main/docs/gmock_cook_book.md#understanding-uninteresting-vs-unexpected-calls-uninteresting-vs-unexpected)

2024-06-17 11:10 UTC, artek-koltun reviewed
Hej @SergiusTheBest I want to add a small improvement to this nice library. Pls let me know if you have any comments!

2024-06-18 07:41 UTC, intelfisz approved these changes
LGTM

2024-06-18 08:33 UTC, SergiusTheBest commented
@artek-koltun Thank you for the PR! Let me check it.

2024-06-19 11:02 UTC, SergiusTheBest requested changes
Everything works good! Some minor changes are requested.

2024-06-19 11:16 UTC, artek-koltun commented on README.md
> +Also you can use `ON_GLOBAL_CALL` to specify default behavior. `ON_NICE_GLOBAL_CALL` can be used to set default behavior with suppressed warning when this mock was actually called.
Ooops! Good catch! My oversight

2024-06-19 11:17 UTC, artek-koltun commented on include/gmock-global/gmock-global.h
> +#define _GLOBAL_MOCK_CALL(name, method, callType, mockType) \
Renamed to `GLOBAL_MOCK_INTERNAL_CALL`
Thank you for sharing the link

2024-06-19 11:19 UTC, SergiusTheBest approved these changes

2024-06-19 11:19 UTC, merged

2024-06-19 11:21 UTC, SergiusTheBest commented
@artek-koltun Perfect! Thank you!

2024-06-19 11:25 UTC, artek-koltun commented
> @artek-koltun Perfect! Thank you!

@SergiusTheBest thank you for the prompt review!